name: Tauri Build
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            artifact_path: |
              src-tauri/target/release/bundle
              src-tauri/target/release/latex-mfr
          - os: windows-latest
            name: windows
            artifact_path: src-tauri/target/release/bundle
          - os: macos-latest
            name: macos
            artifact_path: src-tauri/target/release/bundle
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libxdo-dev \
            libssl-dev \
            libfuse2
      - name: Install npm deps
        run: npm install
      - name: Build Tauri app
        run: npm run tauri build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundles-${{ matrix.name }}
          path: ${{ matrix.artifact_path }}
